# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app_dashboard_scenario_result:
        class: AppBundle\Services\ScenarioResult

    app_dashboard_check_available:
        class: AppBundle\Services\CheckIsAvailable
        arguments: ['@service_container']
