<?php

namespace AppBundle\Repository;

/**
 * ScenarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScenarioRepository extends \Doctrine\ORM\EntityRepository
{
}
